# Generated by Django 4.1.5 on 2023-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='facility',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='month',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
