# Generated by Django 4.1.5 on 2023-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_disease_facility_disease_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedisease',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم فئة التصنيف'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=150, verbose_name='إسم المرض'),
        ),
    ]
