# Generated by Django 4.1.5 on 2023-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_categoriedisease_name_alter_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedisease',
            name='name',
            field=models.CharField(max_length=150, verbose_name='جميع الأمراض'),
        ),
    ]
