# Generated by Django 4.1.5 on 2023-02-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_disease_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriedisease',
            name='total',
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
    ]
