# Generated by Django 4.1.5 on 2023-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_disease_month_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriedisease',
            name='month_last',
            field=models.IntegerField(blank=True, max_length=7, null=True),
        ),
    ]
