# Generated by Django 4.2.4 on 2023-09-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0016_delete_monthreport_delete_reportdiseaseallfacility_and_more'),
        ('mysite', '0011_alter_categoriedisease_options_alter_disease_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadre',
            name='type',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': True, 'verbose_name': 'المحور', 'verbose_name_plural': 'المحاور'},
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type',
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المحور'),
        ),
        migrations.DeleteModel(
            name='Cadre',
        ),
        migrations.DeleteModel(
            name='TypeCadre',
        ),
        migrations.DeleteModel(
            name='TypeFacility',
        ),
    ]
