# Generated by Django 4.1.5 on 2023-01-27 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.cadre', verbose_name='الطبيب المختص')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.facility', verbose_name='اسم المرفق')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.month')),
            ],
            options={
                'verbose_name': 'أوبئة',
                'verbose_name_plural': 'الترصد الوبائي',
            },
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
            ],
            options={
                'verbose_name': 'تقرير شهري',
                'verbose_name_plural': 'MonthReports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.month',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'تقارير',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.facility',),
        ),
        migrations.CreateModel(
            name='SurveyingDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(max_length=3, verbose_name='العدد')),
                ('Disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.disease', verbose_name='المرض')),
                ('Surveying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventive.surveying', verbose_name='')),
            ],
        ),
    ]
