# Generated by Django 4.1.5 on 2023-01-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('preventive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterModelOptions(
            name='monthreport',
            options={'verbose_name': 'تقرير شهري', 'verbose_name_plural': 'تقارير الترصد الوبائي'},
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'تقرير الترصد الوبائي')], max_length=50, verbose_name='اسم التقرير')),
                ('date_start', models.DateField(verbose_name='من')),
                ('date_end', models.DateField(verbose_name='حتى')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.facility', verbose_name='اسم المرفق')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'تقارير',
            },
        ),
    ]
