# Generated by Django 4.1.5 on 2023-01-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0002_delete_report_alter_monthreport_options_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(choices=[('تقرير الأمراض التي تم إستقبالها في المرافق الطبية', 'تقرير الأمراض التي تم إستقبالها في المرافق الطبية')], max_length=50, verbose_name='اسم التقرير'),
        ),
    ]
