# Generated by Django 4.1.5 on 2023-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0003_alter_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_start',
        ),
        migrations.AddField(
            model_name='report',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, max_length=3, verbose_name='الشهر'),
            preserve_default=False,
        ),
    ]
