# Generated by Django 4.1.5 on 2023-01-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0004_remove_report_date_end_remove_report_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='facility',
            field=models.IntegerField(max_length=5, verbose_name='اسم المرفق'),
        ),
    ]
