# Generated by Django 4.1.5 on 2023-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0005_alter_report_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='facility',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='اسم المرفق'),
        ),
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم التقرير'),
        ),
    ]
