# Generated by Django 4.1.5 on 2023-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0006_alter_report_facility_alter_report_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.IntegerField(blank=True, max_length=150, null=True, verbose_name='اسم التقرير'),
        ),
    ]
