# Generated by Django 4.1.5 on 2023-01-31 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0008_reportdisease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdisease',
            options={'verbose_name': 'تقرير', 'verbose_name_plural': 'تقارير الترصد'},
        ),
    ]
