# Generated by Django 4.1.5 on 2023-01-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_categoriedisease_name_alter_disease_name'),
        ('preventive', '0009_alter_reportdisease_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDiseaseAllFacility',
            fields=[
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'جميع المرافق',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.disease',),
        ),
    ]
