# Generated by Django 4.1.5 on 2023-02-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0010_reportdiseaseallfacility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyingdisease',
            options={'verbose_name': 'الترصد'},
        ),
    ]
