# Generated by Django 4.1.5 on 2023-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0011_alter_surveyingdisease_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveying',
            name='message_id',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
