# Generated by Django 4.2.4 on 2023-08-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_categoriedisease_options_alter_disease_options_and_more'),
        ('preventive', '0012_surveying_message_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdisease',
            options={'verbose_name': 'التقرير اليومي', 'verbose_name_plural': 'التقرير اليومي'},
        ),
        migrations.AlterModelOptions(
            name='surveyingdisease',
            options={'verbose_name': 'مرض', 'verbose_name_plural': 'الأمراض'},
        ),
        migrations.AlterField(
            model_name='surveying',
            name='cadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.cadre', verbose_name='الطبيب المختص'),
        ),
    ]
