# Generated by Django 4.2.4 on 2023-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive', '0013_alter_reportdisease_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveying',
            name='month2',
            field=models.IntegerField(default=1, verbose_name='الشهر'),
            preserve_default=False,
        ),
    ]
