# Generated by Django 4.2.4 on 2023-09-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_cadre_type_delete_month_delete_report_and_more'),
        ('preventive', '0016_delete_monthreport_delete_reportdiseaseallfacility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='facility',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='اسم المحور'),
        ),
        migrations.AlterField(
            model_name='surveying',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.facility', verbose_name='اسم المحور'),
        ),
    ]
