# Generated by Django 4.2.4 on 2023-09-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='مفعل')),
                ('time', models.TimeField(verbose_name='وقت البدء')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=50, verbose_name='اسم المسؤول')),
                ('phone_number', models.BigIntegerField(verbose_name='رقم الهاتف')),
                ('report_day', models.BooleanField(default=False, verbose_name='التقرير اليومي')),
                ('report_wik', models.BooleanField(default=False, verbose_name='التقرير الاسبوعي')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsc.setting')),
            ],
            options={
                'verbose_name': 'Reports',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
