# Generated by Django 4.2.4 on 2023-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperaSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.IntegerField(verbose_name='id_me')),
                ('date_time', models.DateTimeField(verbose_name='date_time')),
            ],
            options={
                'verbose_name': 'OperaSms',
                'verbose_name_plural': 'OperaSmss',
            },
        ),
    ]
